CREATE TABLE [dbo].[Komplex](
    [KomplexID] [int] IDENTITY(1,1) NOT NULL,
    [Name] [nvarchar](100) NULL
PRIMARY KEY CLUSTERED
(
    [KomplexID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

