CREATE TABLE [dbo].[Kostenstelle](
	[KostenstelleID] [int] IDENTITY(1,1) NOT NULL,
	[Bezeichnung] [nchar](100) NOT NULL,
	[GnuCashPath] [nchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[KostenstelleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO