CREATE TABLE [dbo].[Raum](
	[RaumID] [int] IDENTITY(1,1) NOT NULL,
	[WohnungID] [int] NOT NULL,
	[TypID] [int] NOT NULL,
	[Groesse] [decimal](10, 2) NULL,
	[NebenkostenGroesse] [decimal](5, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[RaumID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Raum]  WITH CHECK ADD FOREIGN KEY([WohnungID])
REFERENCES [dbo].[Wohnung] ([WohnungID])
GO

ALTER TABLE [dbo].[Raum]  WITH CHECK ADD FOREIGN KEY([TypID])
REFERENCES [dbo].[Raumtypen] ([TypID])