CREATE TABLE [dbo].[Raumtypen](
	[TypID] [int] IDENTITY(1,1) NOT NULL,
	[TypName] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[TypID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]