CREATE TABLE [dbo].[Wohnung](
	[WohnungID] [int] IDENTITY(1,1) NOT NULL,
	[HausID] [int] NOT NULL,
	[Etage] [nvarchar](50) NULL,
	[LageImHaus] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[WohnungID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Wohnung]  WITH CHECK ADD FOREIGN KEY([HausID])
REFERENCES [dbo].[Haus] ([HausID])