# Generated by Django 5.0.14 on 2025-04-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Einheitstypen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Haus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=100, null=True)),
                ('hausnummer', models.CharField(max_length=10, null=True)),
                ('plz', models.CharField(max_length=10, null=True)),
                ('stadt', models.CharField(max_length=100, null=True)),
                ('groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nebenkosten_groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Komplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nebenkosten_groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kostenstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100, null=True)),
                ('gnucash_path', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mieter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(max_length=20, null=True)),
                ('nachname', models.CharField(max_length=100, null=True)),
                ('kontakt_info', models.CharField(max_length=100, null=True)),
                ('vorname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raumtypen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kostensplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anteil', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('haus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.haus')),
                ('komplex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.komplex')),
                ('kostenstelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.kostenstelle')),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buchungsdatum', models.DateField()),
                ('beschreibung', models.CharField(max_length=200, null=True)),
                ('kostenstelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.kostenstelle')),
            ],
        ),
        migrations.CreateModel(
            name='Mietvertrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mietbeginn', models.DateField(null=True)),
                ('mietende', models.DateField(null=True)),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.mieter')),
            ],
        ),
        migrations.CreateModel(
            name='Forderung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berechnungsdatum', models.DateField()),
                ('bezeichnung', models.CharField(max_length=200)),
                ('gesamtbetrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('split_anteil', models.IntegerField()),
                ('gesamtwohnflaeche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anteilwohnflaeche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anteilbetrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('miettage', models.IntegerField()),
                ('kostensplit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.kostensplit')),
                ('mietvertrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.mietvertrag')),
            ],
        ),
        migrations.CreateModel(
            name='Wohnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.CharField(max_length=50, null=True)),
                ('lage_im_haus', models.CharField(max_length=50, null=True)),
                ('groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nebenkosten_groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('haus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.haus')),
            ],
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groesse', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nebenkosten_groesse', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.raumtypen')),
                ('wohnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.wohnung')),
            ],
        ),
        migrations.AddField(
            model_name='mietvertrag',
            name='wohnung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.wohnung'),
        ),
        migrations.AddField(
            model_name='kostensplit',
            name='wohnung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.wohnung'),
        ),
        migrations.CreateModel(
            name='Komplexteile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=50, null=True)),
                ('typ', models.CharField(max_length=20, null=True)),
                ('haus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.haus')),
                ('komplex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.komplex')),
                ('wohnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hausverwaltung.wohnung')),
            ],
        ),
    ]
