# Generated by Django 5.0.14 on 2025-04-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hausverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forderung',
            name='tageimjahr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forderung',
            name='umlageschluesselMietdauer',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='forderung',
            name='umlageschluesselQM',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='forderung',
            name='umlageschluesselVerbrauch',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='forderung',
            name='miettage',
            field=models.IntegerField(null=True),
        ),
    ]
