# Generated by Django 5.0.14 on 2025-04-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hausverwaltung', '0002_forderung_tageimjahr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mieter',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mieter',
            name='hausnummer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mieter',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mieter',
            name='stadt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mieter',
            name='strasse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mieter',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='anrede',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='kontakt_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='vorname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
